name: guardian_sms
description: Protección inteligente contra smishing y mensajes fraudulentos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # SMS y permisos
  telephony: ^0.2.0
  permission_handler: ^11.0.1
  
  # Estado y navegación
  provider: ^6.0.5
  
  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utilidades
  shared_preferences: ^2.2.2
  http: ^1.1.0
  url_launcher: ^6.2.1
  intl: ^0.18.1
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png