name: guardian_sms
description: Protección inteligente contra smishing y mensajes fraudulentos
publish_to: 'none'
version: 1.0.1+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # SMS y permisos - ESENCIALES
  telephony: ^0.2.0
  permission_handler: ^11.0.1
  
  # Notificaciones - CRÍTICO PARA ALERTAS
  flutter_local_notifications: ^17.2.3
  # flutter_app_badger: ^1.5.0  # Temporalmente deshabilitado (discontinued, incompatible con API 35)

  # Background tasks - CRÍTICO PARA LISTENER
  # workmanager: ^0.5.1
  
  # Estado y navegación
  provider: ^6.1.2
  
  # Base de datos local - ESENCIAL
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utilidades - ÚTILES
  shared_preferences: ^2.2.2
  http: ^1.1.0
  url_launcher: ^6.2.1
  intl: ^0.18.1
  crypto: ^3.0.3  # Para hashing de mensajes (feedback anónimo)
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#5170FF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"